# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fftshift_checkerboard": "01_util.ipynb",
         "cartesian_aberrations": "01_util.ipynb",
         "memory_mb": "01_util.ipynb",
         "memory_gb": "01_util.ipynb",
         "fourier_coordinates_2D": "01_util.ipynb",
         "array_split_divpoints": "01_util.ipynb",
         "R_factor": "01_util.ipynb",
         "distance": "01_util.ipynb",
         "rel_dist": "01_util.ipynb",
         "Param": "01_util.ipynb",
         "validate_standard_param": "01_util.ipynb",
         "format_standard_param": "01_util.ipynb",
         "asParam": "01_util.ipynb",
         "make_default": "01_util.ipynb",
         "PARAM_PREFIX": "01_util.ipynb",
         "HSV_to_RGB": "01a_util_plot.ipynb",
         "P1A_to_HSV": "01a_util_plot.ipynb",
         "imsave": "01a_util_plot.ipynb",
         "plot_complex_multi": "01a_util_plot.ipynb",
         "plot": "01a_util_plot.ipynb",
         "fasta2": "10a_fasta.ipynb",
         "setup_logging": "20_setup.ipynb",
         "configure_node": "20_setup.ipynb",
         "load_smatrix_data_list2": "20_setup.ipynb",
         "initial_probe_amplitude": "20_setup.ipynb",
         "prepare_beam_parameters": "20_setup.ipynb",
         "initial_smatrix": "20_setup.ipynb",
         "report_smatrix_parameters": "20_setup.ipynb",
         "report_initial_probes": "20_setup.ipynb",
         "A": "30_operators.ipynb",
         "AH_S": "30_operators.ipynb",
         "smatrix_phase_factorsBDK": "30_operators.ipynb",
         "smatrix_phase_factorsKB": "30_operators.ipynb",
         "smatrix_forward_kernel": "40_operators.kernels.ipynb",
         "smatrix_backward_kernel_S": "40_operators.kernels.ipynb",
         "phase_factor_kernelDBK": "40_operators.kernels.ipynb",
         "phase_factor_kernelKB": "40_operators.kernels.ipynb",
         "ZernikeProbe2": "50_functional.ipynb",
         "prox_D_gaussian_kernel": "60_loss_functions.ipynb",
         "prox_D_gaussian": "60_loss_functions.ipynb",
         "gradz_poisson_sparse_kernel": "60_loss_functions.ipynb",
         "gradz_poisson_sparse": "60_loss_functions.ipynb",
         "gradz_gaussian_sparse_kernel": "60_loss_functions.ipynb",
         "gradz_gaussian_sparse": "60_loss_functions.ipynb",
         "SMeta": "90_core.ipynb"}

modules = ["util.py",
           "algorithm.py",
           "setup.py",
           "operators.py",
           "kernels.py",
           "core.py"]

doc_url = "https://philipppelz.github.io//smpr3d/"

git_url = "https://github.com/s-matrix/smpr3d/tree/master/"

def custom_doc_links(name): return None
